api/urls.py
from django.urls import path
from api.views import ToDoListAPIView, ToDoDetailAPIView

app_name = 'api'

urlpatterns = [
    path('api/todo/', ToDoListAPIView.as_view(), name='todo-list'),
    path('api/todo/<int:pk>/', ToDoDetailAPIView.as_view(), name='todo-detail'),
]

todo/urls.py
from django.contrib import admin
from django.urls import path, include

from api.views import ToDoListAPIView
from todoapp.views import page_not_found
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('api/v1/', ToDoListAPIView.as_view(), name='api-v1'),
    path('', include('todoapp.urls')),  # Перемещено вниз, под 'api/v1/' шаблон
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns.append(path('__debug__/', include('debug_toolbar.urls')))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todoapp/urls.py
from django.urls import path

from . import views

app_name = 'todoapp'

urlpatterns = [
    # Поменяйте порядок URL-шаблонов
    path('add/', views.ToDoCreateView.as_view(), name='add'),
    path('update/<int:pk>/', views.update, name='update'),
    path('delete/<int:pk>/', views.ToDoDeleteView.as_view(), name='delete'),
    path('', views.IndexView.as_view(), name='index'),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
]

todoapp/models.py
from django.db import models
from users.models import User

class ToDo(models.Model):
    ''' Класс, описывающий модель приложения в бд '''

    title = models.CharField(max_length=150, verbose_name='Название задания')
    is_complete = models.BooleanField('Завершено', default=False)
    time = models.DateTimeField(auto_now_add=True,verbose_name='дата создания')  # дата, создания задания
    user=models.ForeignKey(to=User,on_delete=models.CASCADE,null=True, blank=True, default=None)

    class Meta:
        verbose_name = 'Задание'
        verbose_name_plural = 'Задания'

    def __str__(self):
        return self.title

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    ''' модель для пользователя '''
    image = models.ImageField(upload_to='users_images', null=True, blank=True, default=None, verbose_name='Фото')

todoapp/forms.py
from django import forms
from .models import ToDo

# class ToDoForm(forms.ModelForm):
#
#     class Meta:
#         model=ToDo
#         fields=['title',]
#         widgets={
#             'title':forms.TextInput()
#         }

class ToDoForm(forms.ModelForm):
    class Meta:
        model = ToDo
        fields = ['title']
        widgets = {'title': forms.TextInput()}

    def clean_title(self):
        title = self.cleaned_data.get('title')
        if not title.strip():
            raise forms.ValidationError("Название задачи не может быть пустым.")
        return title

users/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from users.models import User
from django import forms


class UserLoginForm(AuthenticationForm):
    ''' Форма для входа пользователей'''

    class Meta:
        model = User
        fields = ('username', 'password')


class UserRegistrationForm(UserCreationForm):
    ''' Форма для регистрации пользователей'''

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class UserProfileForm(UserChangeForm):
    '''Форма для обновления профиля '''

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'image', 'email',)

api/views.py
from rest_framework import generics
from rest_framework.permissions import IsAuthenticated
from todoapp.models import ToDo
from todoapp.serializers import ToDoSerializer

class ToDoListAPIView(generics.ListCreateAPIView):
    queryset = ToDo.objects.all()
    serializer_class = ToDoSerializer
    permission_classes = [IsAuthenticated]

todoapp/views.py
from django.http import HttpResponseNotFound, HttpResponse
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import ListView
from django.contrib.auth import get_user_model
from rest_framework import generics

from users.models import User
from .forms import ToDoForm
from .models import ToDo
from django.views.generic.edit import CreateView, DeleteView

class IndexView(ListView):
    model = ToDo
    template_name = 'todoapp/index.html'
    title = "Главная страница"
    ordering = ['-id']  # Указывает порядок сортировки


class ToDoCreateView(CreateView):
    model = ToDo
    template_name = 'todoapp/index.html'
    form_class = ToDoForm
    success_url = reverse_lazy('todoapp:index')

    def form_valid(self, form):
        # Получаем пользователя из запроса
        user = self.request.user
        User = get_user_model()
        title = form.cleaned_data.get('title', False)

        if user.is_authenticated and isinstance(user, User) and title:
            form.instance.user = user
            form.instance.is_complete = False
            return super().form_valid(form)
        else:
            return HttpResponse("<h1>Статьи по категориям</h1>")


def update(request, pk):
    '''Класс обновления задания'''
    todo = ToDo.objects.get(id=pk)
    todo.is_complete = not todo.is_complete
    todo.save()
    return redirect('todoapp:index')


class ToDoDeleteView(DeleteView):
    '''Класс удаления задания задания'''
    model = ToDo
    template_name = 'todoapp/index.html'
    success_url = reverse_lazy('todoapp:index')


def page_not_found(request, exception):
    '''
    Функция обработчика исключения, когда страница не найдена
    '''
    return HttpResponseNotFound('<h1>Страница не найдена</h1>')

users/views.py
from django.http import HttpResponse
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse
from users.forms import UserLoginForm, UserRegistrationForm, UserProfileForm
from django.contrib import auth



def login(request):
    ''' Функция для авторизации и аунтефикации '''
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user:  # если пользователь у нас есть
                auth.login(request, user)  # мы его авторизуем
                return HttpResponseRedirect(reverse('todoapp:index'))
    else:
        form = UserLoginForm()
    context = {'form': form}
    return render(request, 'users/login.html', context)


def register(request):
    ''' Функция для регистрации пользователя '''
    if request.method == 'POST':
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('todoapp:index'))
    else:
        form = UserRegistrationForm()
    context = {'form': form}
    return render(request, 'users/register.html', context)

def profile(request):
    if request.method == 'POST':
        form = UserProfileForm(instance=request.user, data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('todoapp:index'))
    else:
        form = UserProfileForm(instance=request.user)
    context = {'form': form}
    return render(request, 'users/profile.html', context)


def logout_user(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('todoapp:index'))

todoapp/templates/todoapp/base.html
<!doctype html>
{% load static %}

<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{ title }} </title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.css">
    <link rel="stylesheet" href="{% static 'todoapp/css/style.css' %}">

</head>
<body>
<!-- Navigation -->
<nav class="ui menu">
    <div class="ui container">
         {% if user.is_authenticated %}
        <ul class="last">
        <a href="{% url 'todoapp:index' %}">Главная</a> | <a href="{% url 'users:profile' %}">Профиль</a>
        </ul>
         {% else %}
        <div class="right menu">
            <ul class="last">
                <a href="{% url 'users:register' %}">Регистрация</a> | <a href="{% url 'users:login' %}">Войти</a>
            </ul>
            {% endif %}
        </div>
    </div>
</nav>


{% block content %}

{% endblock content %}
<script src="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.js"></script>
</body>
</html>

todoapp/templates/todoapp/index.html
{% extends 'todoapp/base.html' %}
{% load my_filter %}

{% block content %}

<div style="margin-top: 50px;" class="ui container">
    <h1 class="ui center aligned header">Мой менеджер задач</h1>
    <h3 class="test_style">Управляй своим временем!</h3>
    <form class="ui form" action="{% url 'todoapp:add' %}" method="post">
        {% csrf_token %}
        <div class="field">
            <label for="{{ form.title.id_for_label }}">Новая задача</label>
            {{ form.title }}
            <input type="text" name="title" placeholder="Введите название задачи"><br>
        </div>
        <button class="ui teal basic button" type="submit">Добавить</button>
    </form>

</div>

    {% if user.is_authenticated %}
    {% if user.todo_set.count > 0 %}
        {% for todo in user.todo_set.all|order %}
        <div class="ui segment">
            <p class="ui big header">{{ todo.title }}</p>

            {% if not todo.is_complete %}
            <span class="ui gray label">Не завершено</span>
            <a class="ui primary basic button" href="{% url 'todoapp:update' pk=todo.id %}">Закрыть</a>
            {% else %}
            <span class="ui green label">Завершено</span>
            <a class="ui blue button" href="{% url 'todoapp:update' pk=todo.id %}">Открыть</a>
            {% endif %}

        <form method="post" action="{% url 'todoapp:delete' pk=todo.id %}" style="display: inline;">
          {% csrf_token %}
          <button class="ui negative basic button" type="submit">Удалить</button>
        </form>
      </div>
    {% endfor %}
  {% else %}
    <h4>Нет добавленных задач</h4>
  {% endif %}
{% else %}
  <h4>Для просмотра задач вам необходимо войти в систему.</h4>
{% endif %}



{% endblock content %}

users/templates/users/base.html
<!doctype html>
{% load static %}

<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{ title }} </title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.css">
    <link rel="stylesheet" href="{% static 'users/css/style.css' %}">

</head>
<body>
<!-- Navigation -->
<nav class="ui menu">
    <div class="ui container">
        {% if user.is_authenticated %}
        <ul class="last">
        <a href="{% url 'todoapp:index' %}">Главная</a> | <a href="{% url 'users:profile' %}">Профиль</a>
        </ul>
         {% else %}
        <div class="menu">
            <ul class="last">
                <a href="{% url 'todoapp:index' %}">Главная</a> </a>
            </ul>
        </div>

        <div class="right menu">
            <ul class="last">
                <a href="{% url 'users:register' %}">Регистрация</a> | <a href="{% url 'users:login' %}">Войти</a>
            </ul>
            {% endif %}
        </div>
    </div>
</nav>


{% block content %}

{% endblock content %}
<script src="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.js"></script>
</body>
</html>

users/templates/users/login.html
{% extends 'users/base.html' %}
{% load static %}

{% block content %}
<link href='https://fonts.googleapis.com/css?family=Ubuntu:500' rel='stylesheet' type='text/css'>

<div class="login">
  <div class="login-header">
    <h1>Вход</h1>
  </div>
  <div class="login-form">
    <form action="{% url 'users:login' %}" method="post">
      {% csrf_token %}
      {{ form.username.label_tag }}
      {{ form.username }}
      {{ form.password.label_tag }}
      {{ form.password }}
      <button type="submit" class="btn btn-primary mt-3">Вход</button>
    </form>
  </div>
</div>
<div class="error-page">
  <div class="try-again">Error: Try again?</div>
</div>

<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script src="{% static 'users/js/login.js' %}"></script>
{% endblock content %}

users/templates/users/profile.html
{% extends 'users/base.html' %}
{% load static %}

{% block content %}
<div class="ui container">
    <h1 class="ui header">Личный кабинет</h1>
    <h3>Добро пожаловать, {{ user.username }}!</h3>
    <div class="ui segment">
        <form action="{% url 'users:profile' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="col-lg-12">
                <img width="110" height="110"
                     src="{% if user.image %} {{ user.image.url }} {% else %} {% static 'default_avatar.jpg' %} {% endif %}">
            </div>

            <div class="field">
                <label for="{{ form.first_name.id_for_label }}">Имя:</label>
                {{ form.first_name }}
            </div>

            <p>
            <div class="field">
                <label for="{{ form.last_name.id_for_label }}">Фамилия:</label>
                {{ form.last_name }}
            </div>

            <div class="field">
                <div class="ui input">
                    {{ form.image }}
                    <label for="{{ form.image.id_for_label }}">Выберите изображение:</label>

                </div>
            </div>

            <p>
            <div class="field">
                <label for="{{ form.email.id_for_label }}">Адрес электронной почты:</label>
                {{ form.email }}
            </div>

            <button type="submit" class="ui button primary">Сохранить изменения</button>
        </form>

        <p>
        <p><a href="{% url 'users:logout' %}" class="ui button negative">Выйти</a></p>
    </div>
</div>
{% endblock content %}

users/templates/users/register.html
{% extends 'users/base.html' %}
{% load static %}

{% block content %}
<link href='https://fonts.googleapis.com/css?family=Ubuntu:500' rel='stylesheet' type='text/css'>

<div class="login">
  <div class="login-header">
    <h1>Регистрация</h1>
  </div>
  <div class="login-form">
    <form action="{% url 'users:register' %}" method="post">
      {% csrf_token %}
      {{ form.username.label_tag }}
      {{ form.username }}
      {{ form.email.label_tag }}
      {{ form.email }}
      {{ form.password1.label_tag }}
      {{ form.password1 }}
      {{ form.password2.label_tag }}
      {{ form.password2 }}
      <button type="submit" class="btn btn-primary mt-3">Зарегистрироваться</button>
    </form>
  </div>
</div>
<div class="error-page">
  <div class="try-again">Error: Try again?</div>
</div>

<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script src="{% static 'users/js/register.js' %}"></script>
{% endblock content %}